-- ============================================================================
--  Traducciones del contenido editable (en, it, fr, zh). El español sigue en
--  las columnas de siempre; el resto va en "traducciones" jsonb.
--  GENERADO por scripts/generar-traducciones.mjs — no editar a mano.
--  Idempotente: correrlo otra vez repone las traducciones de fábrica.
-- ============================================================================

set search_path = mariposas, public, extensions;

alter table especies           add column if not exists traducciones jsonb not null default '{}'::jsonb;
alter table proyectos_sociales add column if not exists traducciones jsonb not null default '{}'::jsonb;
alter table proyectos_sociales add column if not exists unidad_singular text;
alter table impacto_registros  add column if not exists traducciones jsonb not null default '{}'::jsonb;
alter table ajustes            add column if not exists traducciones jsonb not null default '{}'::jsonb;

-- La vista pública del impacto tiene que exponer las columnas nuevas.
drop view if exists vista_impacto_global;
create view vista_impacto_global with (security_invoker = true) as
select ps.id, ps.slug, ps.nombre, ps.descripcion, ps.unidad, ps.unidad_singular, ps.emoji,
       ps.meta_anual, ps.orden, ps.traducciones,
       coalesce(sum(ir.cantidad), 0) as ejecutado
from proyectos_sociales ps
left join impacto_registros ir on ir.proyecto_id = ps.id
where ps.activo
group by ps.id;
grant select on vista_impacto_global to anon, authenticated;

-- especies usa permisos por columna (el precio no es público): sumar la nueva.
grant select (traducciones) on especies to anon, authenticated;

-- Singular en español de cada unidad ("1 árbol").
update proyectos_sociales set unidad_singular = case unidad
  when 'semillas' then 'semilla'
  when 'árboles'  then 'árbol'
  when 'horas'    then 'hora'
  when 'talleres' then 'taller'
  else unidad end
where unidad_singular is null;

-- Especies
update especies set traducciones = '{"en":{"nombre_comun":"Blue Morpho","region":"Costa Rica","descripcion":"The classic metallic blue. In high demand for exhibits and events."},"it":{"nombre_comun":"Morfo blu","region":"Costa Rica","descripcion":"Il classico blu metallizzato. Molto richiesta per mostre ed eventi."},"fr":{"nombre_comun":"Morpho bleu","region":"Costa Rica","descripcion":"Le classique bleu métallique. Très demandé pour les expositions et les événements."},"zh":{"nombre_comun":"大蓝闪蝶","region":"哥斯达黎加","descripcion":"经典的金属蓝色。在展览和活动中需求量很大。"}}'::jsonb where nombre_cientifico = 'Morpho peleides';
update especies set traducciones = '{"en":{"nombre_comun":"Giant Owl","region":"Costa Rica","descripcion":"Huge eyespots that mimic an owl''s eyes. Exceptionally hardy in transit."},"it":{"nombre_comun":"Farfalla civetta","region":"Costa Rica","descripcion":"Grandi ocelli che imitano gli occhi di una civetta. Molto resistente al trasporto."},"fr":{"nombre_comun":"Papillon hibou géant","region":"Costa Rica","descripcion":"D''immenses ocelles qui imitent les yeux d''un hibou. Très résistant au transport."},"zh":{"nombre_comun":"猫头鹰环蝶","region":"哥斯达黎加","descripcion":"巨大的眼斑酷似猫头鹰的眼睛。非常耐受运输。"}}'::jsonb where nombre_cientifico = 'Caligo memnon';
update especies set traducciones = '{"en":{"nombre_comun":"Monarch","region":"Mesoamerica","descripcion":"The icon of migration. Ideal for educational programs."},"it":{"nombre_comun":"Monarca","region":"Mesoamerica","descripcion":"Simbolo della migrazione. Ideale per i programmi educativi."},"fr":{"nombre_comun":"Monarque","region":"Mésoamérique","descripcion":"L''icône de la migration. Idéal pour les programmes éducatifs."},"zh":{"nombre_comun":"帝王蝶","region":"中美洲","descripcion":"迁徙的标志性物种。非常适合科普教育项目。"}}'::jsonb where nombre_cientifico = 'Danaus plexippus';
update especies set traducciones = '{"en":{"nombre_comun":"Glasswing","region":"Costa Rica","descripcion":"Transparent wings. A photographer''s favorite."},"it":{"nombre_comun":"Ali di vetro","region":"Costa Rica","descripcion":"Ali trasparenti. La preferita dei fotografi."},"fr":{"nombre_comun":"Papillon de verre","region":"Costa Rica","descripcion":"Des ailes transparentes. Le préféré des photographes."},"zh":{"nombre_comun":"透翅蝶","region":"哥斯达黎加","descripcion":"翅膀透明，深受摄影师喜爱。"}}'::jsonb where nombre_cientifico = 'Greta oto';
update especies set traducciones = '{"en":{"nombre_comun":"Zebra Longwing","region":"Central America","descripcion":"Slow, eye-catching flight. Excellent for open butterfly houses."},"it":{"nombre_comun":"Zebra dalle ali lunghe","region":"America centrale","descripcion":"Volo lento e appariscente. Eccellente per le case delle farfalle aperte."},"fr":{"nombre_comun":"Zèbre à longues ailes","region":"Amérique centrale","descripcion":"Vol lent et spectaculaire. Excellent pour les serres à papillons ouvertes."},"zh":{"nombre_comun":"斑马长翅蝶","region":"中美洲","descripcion":"飞行缓慢而引人注目。非常适合开放式蝴蝶馆。"}}'::jsonb where nombre_cientifico = 'Heliconius charithonia';
update especies set traducciones = '{"en":{"nombre_comun":"King Swallowtail","region":"Costa Rica","descripcion":"Vivid yellow with pronounced tails."},"it":{"nombre_comun":"Coda di rondine reale","region":"Costa Rica","descripcion":"Giallo intenso con code pronunciate."},"fr":{"nombre_comun":"Porte-queue de Thoas","region":"Costa Rica","descripcion":"Jaune intense, avec des queues prononcées."},"zh":{"nombre_comun":"托阿斯凤蝶","region":"哥斯达黎加","descripcion":"明亮的黄色，尾突明显。"}}'::jsonb where nombre_cientifico = 'Papilio thoas';
update especies set traducciones = '{"en":{"nombre_comun":"Malachite","region":"Costa Rica","descripcion":"Translucent jade green. Remarkably long-lived in captivity."},"it":{"nombre_comun":"Malachite","region":"Costa Rica","descripcion":"Verde giada traslucido. Molto longeva in cattività."},"fr":{"nombre_comun":"Malachite","region":"Costa Rica","descripcion":"Vert jade translucide. Très grande longévité en captivité."},"zh":{"nombre_comun":"孔雀石蛱蝶","region":"哥斯达黎加","descripcion":"半透明的翡翠绿色。人工饲养下寿命很长。"}}'::jsonb where nombre_cientifico = 'Siproeta stelenes';
update especies set traducciones = '{"en":{"nombre_comun":"Eighty-eight","region":"Costa Rica","descripcion":"A clear \"88\" drawn on the underside of its hindwings."},"it":{"nombre_comun":"Ottantotto","region":"Costa Rica","descripcion":"Un \"88\" disegnato sulle ali posteriori."},"fr":{"nombre_comun":"Quatre-vingt-huit","region":"Costa Rica","descripcion":"Le « 88 » dessiné sur les ailes postérieures."},"zh":{"nombre_comun":"88 蛱蝶","region":"哥斯达黎加","descripcion":"后翅上绘有「88」的图案。"}}'::jsonb where nombre_cientifico = 'Diaethria astala';

-- Proyectos sociales
update proyectos_sociales set traducciones = '{"en":{"nombre":"Apple seeds planted","descripcion":"We buy and plant apple seeds with highland farming families to help diversify their crops.","unidad":"seeds","unidad_singular":"seed"},"it":{"nombre":"Semi di melo piantati","descripcion":"Acquistiamo e piantiamo semi di melo con le famiglie contadine d''altura per diversificare le loro colture.","unidad":"semi","unidad_singular":"seme"},"fr":{"nombre":"Graines de pommier semées","descripcion":"Nous achetons et semons des graines de pommier avec des familles des hauteurs pour diversifier leurs cultures.","unidad":"graines","unidad_singular":"graine"},"zh":{"nombre":"已播种的苹果种子","descripcion":"我们购买苹果种子，并与高海拔地区的家庭一起播种，帮助他们实现作物多样化。","unidad":"粒种子","unidad_singular":"粒种子"}}'::jsonb where slug = 'semillas-manzano';
update proyectos_sociales set traducciones = '{"en":{"nombre":"Native trees planted","descripcion":"Reforestation with butterfly host plants: madero negro, guarumo and passionflower.","unidad":"trees","unidad_singular":"tree"},"it":{"nombre":"Alberi autoctoni piantati","descripcion":"Riforestazione con piante ospiti delle farfalle: madero negro, guarumo e passiflora.","unidad":"alberi","unidad_singular":"albero"},"fr":{"nombre":"Arbres indigènes plantés","descripcion":"Reboisement avec des espèces hôtes de papillons : madero negro, guarumo, passiflore.","unidad":"arbres","unidad_singular":"arbre"},"zh":{"nombre":"已种植的本土树木","descripcion":"以蝴蝶寄主植物进行植树造林：麻栎豆（madero negro）、号角树（guarumo）、西番莲。","unidad":"棵树","unidad_singular":"棵树"}}'::jsonb where slug = 'arboles-nativos';
update proyectos_sociales set traducciones = '{"en":{"nombre":"Forest under protection","descripcion":"Square meters of forest under no-logging agreements, funded by our sales.","unidad":"m²","unidad_singular":"m²"},"it":{"nombre":"Foresta protetta","descripcion":"Metri quadrati di foresta con accordi di non disboscamento, finanziati dalle vendite.","unidad":"m²","unidad_singular":"m²"},"fr":{"nombre":"Forêt en conservation","descripcion":"Mètres carrés de forêt placés sous accord de non-abattage, financés par les ventes.","unidad":"m²","unidad_singular":"m²"},"zh":{"nombre":"受保护的森林","descripcion":"由销售收入资助、签订禁伐协议的森林面积（平方米）。","unidad":"平方米","unidad_singular":"平方米"}}'::jsonb where slug = 'metros-conservados';
update proyectos_sociales set traducciones = '{"en":{"nombre":"Hours of rural employment","descripcion":"Paid hours for the breeding families who supply us, most of them led by women.","unidad":"hours","unidad_singular":"hour"},"it":{"nombre":"Ore di lavoro rurale","descripcion":"Ore retribuite alle famiglie di allevatori che ci riforniscono, per lo più guidate da donne.","unidad":"ore","unidad_singular":"ora"},"fr":{"nombre":"Heures d''emploi rural","descripcion":"Heures rémunérées aux familles d''éleveurs qui nous approvisionnent, pour la plupart dirigées par des femmes.","unidad":"heures","unidad_singular":"heure"},"zh":{"nombre":"农村就业工时","descripcion":"支付给为我们供货的养殖家庭的工时，其中大多数家庭由女性当家。","unidad":"小时","unidad_singular":"小时"}}'::jsonb where slug = 'horas-empleo';
update proyectos_sociales set traducciones = '{"en":{"nombre":"School ecology workshops","descripcion":"Free workshops at rural schools on pollinators and the butterfly life cycle.","unidad":"workshops","unidad_singular":"workshop"},"it":{"nombre":"Laboratori scolastici di ecologia","descripcion":"Laboratori gratuiti nelle scuole rurali su impollinatori e ciclo di vita delle farfalle.","unidad":"laboratori","unidad_singular":"laboratorio"},"fr":{"nombre":"Ateliers scolaires d''écologie","descripcion":"Ateliers gratuits dans les écoles rurales sur les pollinisateurs et le cycle de vie.","unidad":"ateliers","unidad_singular":"atelier"},"zh":{"nombre":"校园生态工作坊","descripcion":"在农村学校免费举办关于传粉者和生命周期的工作坊。","unidad":"场工作坊","unidad_singular":"场工作坊"}}'::jsonb where slug = 'talleres-escolares';

-- Bitácora (por el texto en español de cada entrada)
update impacto_registros set traducciones = '{"en":{"detalle":"Delivered to 14 families in Cerro Alto"},"it":{"detalle":"Consegna a 14 famiglie di Cerro Alto"},"fr":{"detalle":"Remise à 14 familles de Cerro Alto"},"zh":{"detalle":"向 Cerro Alto 的 14 户家庭交付"}}'::jsonb where detalle = 'Entrega a 14 familias de Cerro Alto';
update impacto_registros set traducciones = '{"en":{"detalle":"Second delivery + grafting training"},"it":{"detalle":"Seconda consegna + formazione sull''innesto"},"fr":{"detalle":"Deuxième remise + formation au greffage"},"zh":{"detalle":"第二次交付及嫁接培训"}}'::jsonb where detalle = 'Segunda entrega + capacitación de injerto';
update impacto_registros set traducciones = '{"en":{"detalle":"La Cima community nursery"},"it":{"detalle":"Vivaio comunitario di La Cima"},"fr":{"detalle":"Pépinière communautaire de La Cima"},"zh":{"detalle":"La Cima 社区苗圃"}}'::jsonb where detalle = 'Vivero comunitario de La Cima';
update impacto_registros set traducciones = '{"en":{"detalle":"World Water Day reforestation drive"},"it":{"detalle":"Giornata di riforestazione per la Giornata mondiale dell''acqua"},"fr":{"detalle":"Journée de reboisement pour la Journée de l''eau"},"zh":{"detalle":"世界水日植树造林活动"}}'::jsonb where detalle = 'Jornada de reforestación Día del Agua';
update impacto_registros set traducciones = '{"en":{"detalle":"Los Ángeles creek biological corridor"},"it":{"detalle":"Corridoio biologico del torrente Los Ángeles"},"fr":{"detalle":"Corridor biologique du ruisseau Los Ángeles"},"zh":{"detalle":"Los Ángeles 溪生物走廊"}}'::jsonb where detalle = 'Corredor biológico quebrada Los Ángeles';
update impacto_registros set traducciones = '{"en":{"detalle":"Conservation agreement, San Isidro farm"},"it":{"detalle":"Accordo di conservazione, tenuta San Isidro"},"fr":{"detalle":"Accord de conservation du domaine San Isidro"},"zh":{"detalle":"San Isidro 农场保护协议"}}'::jsonb where detalle = 'Acuerdo de conservación finca San Isidro';
update impacto_registros set traducciones = '{"en":{"detalle":"Agreement expanded, northern sector"},"it":{"detalle":"Ampliamento dell''accordo, settore nord"},"fr":{"detalle":"Extension de l''accord, secteur nord"},"zh":{"detalle":"协议扩展至北部区域"}}'::jsonb where detalle = 'Ampliación del acuerdo, sector norte';
update impacto_registros set traducciones = '{"en":{"detalle":"First four-month period: 9 breeding families"},"it":{"detalle":"Primo quadrimestre: 9 famiglie di allevatori"},"fr":{"detalle":"Premier quadrimestre : 9 familles d''éleveurs"},"zh":{"detalle":"第一个四个月周期：9 户养殖家庭"}}'::jsonb where detalle = 'Primer cuatrimestre: 9 familias criadoras';
update impacto_registros set traducciones = '{"en":{"detalle":"Second four-month period: 11 breeding families"},"it":{"detalle":"Secondo quadrimestre: 11 famiglie di allevatori"},"fr":{"detalle":"Deuxième quadrimestre : 11 familles d''éleveurs"},"zh":{"detalle":"第二个四个月周期：11 户养殖家庭"}}'::jsonb where detalle = 'Segundo cuatrimestre: 11 familias criadoras';
update impacto_registros set traducciones = '{"en":{"detalle":"Schools in San Rafael and Río Segundo"},"it":{"detalle":"Scuole di San Rafael e Río Segundo"},"fr":{"detalle":"Écoles de San Rafael et de Río Segundo"},"zh":{"detalle":"San Rafael 和 Río Segundo 的学校"}}'::jsonb where detalle = 'Escuelas de San Rafael y Río Segundo';
update impacto_registros set traducciones = '{"en":{"detalle":"Sarapiquí school district"},"it":{"detalle":"Circuito scolastico di Sarapiquí"},"fr":{"detalle":"Circonscription scolaire de Sarapiquí"},"zh":{"detalle":"Sarapiquí 学区"}}'::jsonb where detalle = 'Circuito escolar de Sarapiquí';

-- Ajustes del sitio
update ajustes set traducciones = '{"en":{"valor":"Live tropical butterflies, sold and exported from Costa Rica with measurable social impact."},"it":{"valor":"Commercializzazione ed esportazione di farfalle tropicali vive dalla Costa Rica, con un impatto sociale misurabile."},"fr":{"valor":"Commercialisation et exportation de papillons tropicaux vivants depuis le Costa Rica, avec un impact social mesurable."},"zh":{"valor":"从哥斯达黎加销售并出口热带活体蝴蝶，并带来可衡量的社会影响。"}}'::jsonb where clave = 'marca_descripcion';
update ajustes set traducciones = '{"en":{"valor":"San Rafael de Alajuela, Costa Rica"},"it":{"valor":"San Rafael de Alajuela, Costa Rica"},"fr":{"valor":"San Rafael de Alajuela, Costa Rica"},"zh":{"valor":"哥斯达黎加阿拉胡埃拉省圣拉斐尔"}}'::jsonb where clave = 'marca_ubicacion';
update ajustes set traducciones = '{"en":{"valor":"Traders and exporters of live tropical butterflies. San Rafael de Alajuela, Costa Rica."},"it":{"valor":"Commercializzazione ed esportazione di farfalle tropicali vive. San Rafael de Alajuela, Costa Rica."},"fr":{"valor":"Commercialisation et exportation de papillons tropicaux vivants. San Rafael de Alajuela, Costa Rica."},"zh":{"valor":"热带活体蝴蝶贸易与出口商。哥斯达黎加阿拉胡埃拉省圣拉斐尔。"}}'::jsonb where clave = 'marca_pie';
update ajustes set traducciones = '{"en":{"valor":"They leave Costa Rica as pupae and emerge in your butterfly house."},"it":{"valor":"Partono come pupe dalla Costa Rica e sfarfallano nella tua casa delle farfalle."},"fr":{"valor":"Chrysalides au départ du Costa Rica, papillons à l''arrivée dans votre serre."},"zh":{"valor":"以蛹的形态从哥斯达黎加启程，在您的蝴蝶馆中破蛹而出。"}}'::jsonb where clave = 'inicio_titular';
update ajustes set traducciones = '{"en":{"valor":"We supply eight tropical species and export them live to butterfly houses, museums and science centers. We work with Costa Rican breeders, keep a recorded cold chain from end to end, and replace every pupa that doesn''t emerge."},"it":{"valor":"Commercializziamo otto specie tropicali e le esportiamo vive a case delle farfalle, musei e centri scientifici. Lavoriamo con allevamenti costaricani, con una catena del freddo registrata dall''inizio alla fine, e sostituiamo ogni pupa che non si schiude."},"fr":{"valor":"Nous commercialisons huit espèces tropicales et les exportons vivantes vers des serres à papillons, des musées et des centres de sciences. Nous travaillons avec des élevages costaricains, avec une chaîne du froid enregistrée de bout en bout et le remplacement de toute chrysalide qui n''éclot pas."},"zh":{"valor":"我们经营八个热带蝴蝶品种，以活体形式出口至蝴蝶馆、博物馆和科学中心。我们与哥斯达黎加养殖户合作，全程冷链均有温度记录，任何未能羽化的蛹都将免费补发。"}}'::jsonb where clave = 'inicio_entradilla';
update ajustes set traducciones = '{"en":{"valor":"38,420"},"it":{"valor":"38.420"},"fr":{"valor":"38 420"},"zh":{"valor":"38,420"}}'::jsonb where clave = 'cifra1_valor';
update ajustes set traducciones = '{"en":{"valor":"butterflies exported since 2019"},"it":{"valor":"farfalle esportate dal 2019"},"fr":{"valor":"papillons exportés depuis 2019"},"zh":{"valor":"自 2019 年以来出口的蝴蝶数量"}}'::jsonb where clave = 'cifra1_texto';
update ajustes set traducciones = '{"en":{"valor":"97.4%"},"it":{"valor":"97,4%"},"fr":{"valor":"97,4 %"},"zh":{"valor":"97.4%"}}'::jsonb where clave = 'cifra2_valor';
update ajustes set traducciones = '{"en":{"valor":"emerge healthy on arrival"},"it":{"valor":"sfarfallano sane all''arrivo a destinazione"},"fr":{"valor":"éclosent en bonne santé à destination"},"zh":{"valor":"抵达目的地后健康羽化"}}'::jsonb where clave = 'cifra2_texto';
update ajustes set traducciones = '{"en":{"valor":"11"},"it":{"valor":"11"},"fr":{"valor":"11"},"zh":{"valor":"11"}}'::jsonb where clave = 'cifra3_valor';
update ajustes set traducciones = '{"en":{"valor":"countries with recurring shipments"},"it":{"valor":"paesi con spedizioni ricorrenti"},"fr":{"valor":"pays avec des envois réguliers"},"zh":{"valor":"个国家定期发货"}}'::jsonb where clave = 'cifra3_texto';
update ajustes set traducciones = '{"en":{"valor":"Nine days from the moment you place your order"},"it":{"valor":"Nove giorni da quando confermi l''ordine"},"fr":{"valor":"Neuf jours après la validation de votre commande"},"zh":{"valor":"从您确认订单起，只需九天"}}'::jsonb where clave = 'ciclo_titulo';
update ajustes set traducciones = '{"en":{"valor":"A pupa holds for ten to fourteen days before it emerges. Every step is timed so it arrives with room to spare, not just in time."},"it":{"valor":"La pupa resiste da dieci a quattordici giorni prima di schiudersi. Tutto il processo è calibrato perché arrivi con margine, non all''ultimo momento."},"fr":{"valor":"La chrysalide tient entre dix et quatorze jours avant d''éclore. Tout le processus est calibré pour qu''elle arrive avec de la marge, et non tout juste."},"zh":{"valor":"蛹在羽化前可维持十到十四天。整个流程都经过精心安排，确保货物留有充足余量送达，而不是踩着时间点。"}}'::jsonb where clave = 'ciclo_texto';
update ajustes set traducciones = '{"en":{"valor":"0|Confirmation|We lock in species, quantities and flight date.\n3|Collection and selection|We receive pupae from our breeders and discard any that look doubtful.\n5|Cold packing|Cotton, cooling gel and a temperature logger.\n9|Delivery|Customs, phytosanitary inspection and on to your butterfly house door."},"it":{"valor":"0|Conferma|Definiamo specie, quantità e data di volo.\n3|Raccolta e selezione|Riceviamo le pupe dagli allevamenti e scartiamo quelle dubbie.\n5|Imballaggio refrigerato|Cotone, gel refrigerante e registratore di temperatura.\n9|Consegna|Dogana, ispezione fitosanitaria e consegna alla porta della tua casa delle farfalle."},"fr":{"valor":"0|Confirmation|Nous arrêtons les espèces, les quantités et la date du vol.\n3|Collecte et tri|Nous réceptionnons les chrysalides des élevages et écartons toute chrysalide douteuse.\n5|Emballage réfrigéré|Coton, gel réfrigérant et enregistreur de température.\n9|Livraison|Douane, inspection phytosanitaire et livraison jusqu''à la porte de votre serre à papillons."},"zh":{"valor":"0|确认订单|确定品种、数量和航班日期。\n3|收集与筛选|从养殖户处收货，剔除一切存疑的蛹。\n5|冷藏包装|棉垫、冷却凝胶和温度记录仪。\n9|送达|清关、植物检疫查验，直至送到蝴蝶馆门口。"}}'::jsonb where clave = 'ciclo_pasos';
update ajustes set traducciones = '{"en":{"valor":"Minimum per species|25 pupae\nTransit temperature|13 °C to 16 °C\nDocuments included|CITES permit and phytosanitary certificate\nNon-viable pupae|Replaced free of charge in your next shipment"},"it":{"valor":"Minimo per specie|25 pupe\nTemperatura di transito|Da 13 °C a 16 °C\nDocumenti inclusi|Permesso CITES e certificato fitosanitario\nPupe non vitali|Sostituite senza costi nella spedizione successiva"},"fr":{"valor":"Minimum par espèce|25 chrysalides\nTempérature de transit|13 °C à 16 °C\nDocuments inclus|Permis CITES et certificat phytosanitaire\nChrysalides non viables|Remplacées gratuitement lors de l''envoi suivant"},"zh":{"valor":"每个品种起订量|25 枚蛹\n运输温度|13 °C 至 16 °C\n随附文件|CITES 许可证及植物检疫证书\n无法羽化的蛹|在下一批货物中免费补发"}}'::jsonb where clave = 'envio_condiciones';
update ajustes set traducciones = '{"en":{"valor":"They''re exported as pupae, the stage at which the insect best withstands travel. They ship in cotton-lined trays with cooling gel and a temperature logger that''s read when the box is opened."},"it":{"valor":"Vengono esportate allo stadio di pupa, la fase in cui l''insetto sopporta meglio il viaggio. Viaggiano in vassoi di cotone con gel refrigerante e un registratore di temperatura che si legge all''apertura della scatola."},"fr":{"valor":"Elles sont exportées au stade de chrysalide, lorsque l''insecte supporte le mieux le transport. Elles voyagent sur des plateaux de coton avec du gel réfrigérant et un enregistreur de température, relevé à l''ouverture du colis."},"zh":{"valor":"蝴蝶以蛹的形态出口，这是昆虫最能承受运输的阶段。蛹装在铺有棉垫的托盘中，配有冷却凝胶和温度记录仪，开箱时即可读取温度数据。"}}'::jsonb where clave = 'envio_texto';

notify pgrst, 'reload schema';
